### ISSUE TITLE
Can not add npm module to nuxtron project.

### ISSUE THREAD

**Issue by almas** [saltyshiomix/nuxtron#14]
I created a new nuxtron project.

Then I added a module with command below:
`yarn add tsparticles`

Then I imported below code to pages/index.vue
`import { tsParticles } from "tsparticles";`

Then I added a "mounted" and added below code to mounted:
`tsParticles.load("animated-bg", {});`

Then I run it with
`yarn run dev`

But it does not work.
It can not find module "tsparticles" for import.
 
What did I do wrong?

**Comment by matteobruni** [comment]
Hi @almas, if you are using tsParticles `1.16.0` version try upgrade to version `1.16.1`, that should fix the issue.

**Comment by almas** [comment]
@matteobruni  Thank you very much. I just upgraded and it resolved my problem.
