### ISSUE TITLE
Server side not working

### ISSUE THREAD

**Issue by Ethan-Hill** [saltyshiomix/nuxtron#20]
Im currently using [Nuxtron](https://github.com/saltyshiomix/nuxtron) to make a nuxt desktop app and im using a auth module [Auth Module](https://github.com/nuxt-community/auth-module). I see when i build the exe the backend server stops working and any reqests being made fail due to the localhost server not running. I know it's not running because the build requests work when i have the dev mode running also.

[Video of the Error](https://www.dropbox.com/s/ubgopz4yo9y2a76/fIGsQC8XZk.mp4?dl=0)

Any ideas on why or what to do with this?

**Comment by AkshayCloudAnalogy** [comment]
Same issue.
Any solutions for this?

**Comment by Ethan-Hill** [comment]
> Same issue.
> Any solutions for this?

I dont think i did get it to work but feel welcome to take what i had to work off of.
[Gitty](https://github.com/Ethan-Hill/Gitty)
