### ISSUE TITLE
SPA mode example

### ISSUE THREAD

**Issue by dzeso** [saltyshiomix/nuxtron#5]
Could you make SPA mode example please ( mode: 'spa' in nuxt.confige.js)? Your examples don't work in SPA mode after npm run build. Something wrong with routes

**Comment by Gimanh** [comment]
> Could you make SPA mode example please ( mode: 'spa' in nuxt.confige.js)? Your examples don't work in SPA mode after npm run build. Something wrong with routes

I have the same problem. 
If you find a solution, let me know please.
My reproduction link https://github.com/Gimanh/ZVION/tree/spa-bug

**Comment by Gimanh** [comment]
Hi!
Here is my solution with example https://github.com/Gimanh/ZVION/tree/spa-bug was tested (dev, build) with typescript.
Fork is https://github.com/Gimanh/nuxtron/commit/b1fbbf4d3eed3b044f39b24d52460447bd6a4d42
Everything works fine :)

**Comment by Gimanh** [comment]
> Could you make SPA mode example please ( mode: 'spa' in nuxt.confige.js)? Your examples don't work in SPA mode after npm run build. Something wrong with routes

Working config for JavaScript and updated readme
See last commits 
https://github.com/Gimanh/nuxtron
